### ISSUE TITLE
jnasmartcardio Submodule Refers to Non-existent Commit

### ISSUE THREAD

**Issue by dsanders11** [martinpaljak/apdu4j#13]
Trying to checkout a fork of this repository with the Github tool gives the following error message:

> The submodule at "ext/jnasmartcardio" points to commit "fb038bfa5f429d6292dfaaa90f2b71652b4d3e29", which does not exist.

I haven't found a way to clean it up, it leaves the repo in a pretty FUBAR state.

**Comment by martinpaljak** [comment]
Thanks for noticing, will check

**Comment by martinpaljak** [comment]
This has been "fixed" by using Maven dependencies.
