### ISSUE TITLE
Why does the devices have some number referenced at the end?

### ISSUE THREAD

**Issue by qxlsz** [martinpaljak/apdu4j#17]
when i do sc -l
i get 

[ ] Gemalto Ezio Shield 01 00
[*] ACS ACR 38U-CCID 02 00

But what does 01 00 and 02 00 even mean

**Comment by qxlsz** [comment]
any thoughts on this ?

**Comment by qxlsz** [comment]
@martinpaljak

**Comment by martinpaljak** [comment]
This comes from libccid/pcsc-lite
