### ISSUE TITLE
Pilot Error or Jitpack Error? HTTP 403 for requests for any tag of apdu4j

### ISSUE THREAD

**Issue by lonniev** [martinpaljak/apdu4j#50]
`2020.12.09 11:23:48 INFO  [error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://jitpack.io/com/github/martinpaljak/apdu4j_2/13/apdu4j-tool/20.08.12/apdu4j-tool-20.08.12.pom (Server returned HTTP response code: 403 for URL: https://jitpack.io/com/github/martinpaljak/apdu4j_2/13/apdu4j-tool/20.08.12/apdu4j-tool-20.08.12.pom) while downloading https://jitpack.io/com/github/martinpaljak/apdu4j_2/13/apdu4j-tool/20.08.12/apdu4j-tool-20.08.12.pom`

The SBT build setup for credentials to realms and the authorization token as username all _appear_ to be proper - but this is my first use of the JitPack repository.

Any other pilot errors to go fix?

**Comment by martinpaljak** [comment]
I have no idea about jitpack not intend to support it.

If you want builds of apdu4j please use `https://javacard.pro/maven/` as the repository.

**Comment by lonniev** [comment]
I think that is a great resolution! Thank you. (Wasn't here at your project, though, where I was advised to use JitPack? This is the first time I have encountered it.)

**Comment by lonniev** [comment]
Just for the record. Pilot Error. SBT's libraryDependency statement/syntax will append an additional build tag to the stated artifactId when the "%%" operator is used rather than the simple "%" concatenation. I should have paid more attention to where "_2/13" was getting injected into the otherwise valid request URL.

Sorry to trouble you.
