### ISSUE TITLE
Could not probe PinPad: SCardControl got response 0x80100016 (SCARD_E_NOT_TRANSACTED: An attempt was made to end a non-existent transaction.)

### ISSUE THREAD

**Issue by mohsenMgh** [martinpaljak/apdu4j#6]
Hello Martin
thanks for your good utility. I have a problem with apdu4j.  I can probe() successfully but when i want to implement "verifyPinDirect" to verify pin by pinpad in linux, pcsc return the exception "Could not probe PinPad: SCardControl got response 0x80100016 (SCARD_E_NOT_TRANSACTED: An attempt was made to end a non-existent transaction.)". My card reader is acr83 from acs corporation. I think it is because the funtcion "SCardBeginTransaction" from PCSC is not called and there is no such function in smartcardio or apdu4j. 
1- whether my point is right or not? 
2- Does apdu4j support secure pin entry verification "VERIFY_PIN_DIRECT" ? if true, why there is no sample in your codes?
3- whats your point to I solve my problem?
Thank you very much.

**Comment by martinpaljak** [comment]
You probably send an incorrect pinpad block to the reader. Also, ACR83 is not a CCID reader, so you're on your own with whatever you want to do with the reader.
