### ISSUE TITLE
[Feature] Async BIBO client

### ISSUE THREAD

**Issue by ph4r05** [martinpaljak/apdu4j#61]
Hello, I was wondering whether you plan to add support for asynchronous operations to BIBO class. E.g., 

```java
public interface BIBOAsync extends BIBO {
    CompletableFuture<byte[]> transceiveAsync(byte[] bytes) throws BIBOException;
    CompletableFuture<Void> closeAsync();
}
```

We plan to use async approach as we need to serve many concurrent card requests on our server. Currently, we use blocking API (i.e., applet installation with GPPro), thus we need one worker thread per request. Mainly, the worker thread is blocked while server waits for card to respond over the network (network latency, card latency).

If async API is used, we can scale the server much better (using Kotlin coroutines). 

So I was wondering whether you plan to add async methods or whether we should proceed implementing this on our own. 

Thanks! :)

**Comment by martinpaljak** [comment]
There is https://github.com/martinpaljak/apdu4j/blob/master/core/src/main/java/apdu4j/core/AsynchronousBIBO.java ?

**Comment by ph4r05** [comment]
Ah, great! So the support is already there.I was using older release, apdu4j-core-2020b1, which does not contain async API. 

I ended up doing it on my own, extending `GPSession` and adding

- `selectAsync()`
- `openSecureChannelAsync()`
- `deleteAIDAsync()`
- `loadCapFileAsync()`
- `installAndMakeSelectableAsync()`

Those methods use Async BIBO channel, it works great. Thanks
